<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookingCore\BookingCore.csproj" />
    <ProjectReference Include="..\BookingData\BookingData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.33" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>